Ignore nancy failure if OSS index is down (#394)
* Ignore nancy failure if OSS index is down

* Changelog

* Busybox sed doesn't support `q` so rething the whole thing

* Don't fail when grepping

diff --git a/src/commands/go-test.yaml b/src/commands/go-test.yaml
--- a/src/commands/go-test.yaml
+++ b/src/commands/go-test.yaml
@@ -38,7 +38,16 @@ steps:
   - run:
       name: Check if dependencies have known security vulnerabilities
       command: |
-        CGO_ENABLED=0 go list -json -m all | nancy sleuth --skip-update-check --quiet --exclude-vulnerability-file ./.nancy-ignore --additional-exclude-vulnerability-files ./.nancy-ignore.generated
+        set +e
+        CGO_ENABLED=0 go list -json -m all | nancy sleuth --skip-update-check --quiet --exclude-vulnerability-file ./.nancy-ignore --additional-exclude-vulnerability-files ./.nancy-ignore.generated | tee ./nancy-results.txt ; nancy_result=(${PIPESTATUS[1]})
+        grep -q 'error accessing OSS Index' nancy-results.txt; grep_result=$?
+        set -e
+        # If nancy gave us a bad exit code AND grep found an OSS index error in the output, then we don't fail the build.
+        if [[ $nancy_result -eq 1 && $grep_result -eq 0 ]]; then
+          echo Ignoring failed scan due to problem with the external scanner.
+          exit 0
+        fi
+        exit $nancy_result
   - run:
       name: Run unit tests
       command: |
