Busybox sed doesn't support `q` so rething the whole thing

diff --git a/src/commands/go-test.yaml b/src/commands/go-test.yaml
--- a/src/commands/go-test.yaml
+++ b/src/commands/go-test.yaml
@@ -38,15 +38,17 @@ steps:
   - run:
       name: Check if dependencies have known security vulnerabilities
       command: |
-        CGO_ENABLED=0 go list -json -m all | nancy sleuth --skip-update-check --quiet --exclude-vulnerability-file ./.nancy-ignore --additional-exclude-vulnerability-files ./.nancy-ignore.generated | sed '/error accessing OSS Index/,$b;$q1'
-        pstats=(${PIPESTATUS[@]})
+        # CGO_ENABLED=0 go list -json -m all | nancy sleuth --skip-update-check --quiet --exclude-vulnerability-file ./.nancy-ignore --additional-exclude-vulnerability-files ./.nancy-ignore.generated | sed '/error accessing OSS Index/,$b;$q1'
+        # pstats=(${PIPESTATUS[@]})
         # Credit for the sed idea to https://unix.stackexchange.com/a/711864.
-        # If nancy gave us a bad exit code AND sed found an OSS index error in the output, then we don't fail the build.
-        if [[ ${pstats[1]} -eq 1 && ${pstats[2]} -eq 0 ]]; then
+        CGO_ENABLED=0 go list -json -m all | nancy sleuth --skip-update-check --quiet --exclude-vulnerability-file ./.nancy-ignore --additional-exclude-vulnerability-files ./.nancy-ignore.generated | tee ./nancy-results.txt ; nancy_result=(${PIPESTATUS[1]})
+        grep -q 'error accessing OSS Index' nancy-results.txt; grep_result=$?
+        # If nancy gave us a bad exit code AND grep found an OSS index error in the output, then we don't fail the build.
+        if [[ $nancy_result -eq 1 && $grep_result -eq 0 ]]; then
           echo Ignoring failed scan due to problem with the external scanner.
           exit 0
         fi
-        exit ${pstats[1]}
+        exit $nancy_result
   - run:
       name: Run unit tests
       command: |
