Apply suggestions from code review

diff --git a/src/commands/package-and-push.yaml b/src/commands/package-and-push.yaml
--- a/src/commands/package-and-push.yaml
+++ b/src/commands/package-and-push.yaml
@@ -76,8 +76,8 @@ steps:
             sleep 5
           done
 
+          echo "Giving up after $tries failures." >&2
           echo "Error pushing changes. See known errors in:" >&2
           echo "https://github.com/giantswarm/architect-orb/blob/master/README.md#push-to-app-catalog" >&2
-          echo "Giving up after $tries failures." >&2
 
           exit $ret
diff --git a/src/commands/push-to-app-collection.yaml b/src/commands/push-to-app-collection.yaml
--- a/src/commands/push-to-app-collection.yaml
+++ b/src/commands/push-to-app-collection.yaml
@@ -77,9 +77,9 @@ steps:
             sleep 5
           done
 
+          echo "Giving up after $tries failures." >&2
           echo "Error pushing changes. See known errors in:" >&2
           echo "https://github.com/giantswarm/architect-orb/blob/master/README.md#push-to-app-collection" >&2
-          echo "Giving up after $tries failures." >&2
 
           exit $ret
   - run: |
