Set config version in App CR in push-to-app-collection (#217)

diff --git a/src/commands/push-to-app-collection.yaml b/src/commands/push-to-app-collection.yaml
--- a/src/commands/push-to-app-collection.yaml
+++ b/src/commands/push-to-app-collection.yaml
@@ -32,7 +32,21 @@ steps:
   - run:
       name: "architect/push-to-app-collection: Generate version"
       command: |
-        architect project version | tee .version
+        architect project version | tee .app_version
+  - run:
+      name: "architect/push-to-app-collection: Find configuration version"
+      command: |
+        echo "====> Make sure Chart.yaml exists"
+        ls helm/<<parameters.app_name>>/Chart.yaml >/dev/null
+        echo "====> Skip if Chart.yaml does not contain the annotation"
+        if ! grep 'config.giantswarm.io/version' helm/<<parameters.app_name>>/Chart.yaml ; then
+          touch .config_version
+          echo "Skip: annotation \"config.giantswarm.io/version\" not found in helm/<<parameters.app_name>>/Chart.yaml"
+          exit 0
+        fi
+        echo "====> Extract annotation value"
+        # Pipe trough xargs to remove quotes.
+        grep 'config.giantswarm.io/version' helm/<<parameters.app_name>>/Chart.yaml | awk '{ print $2 }' | xargs | tee .config_version
   - run:
       name: "architect/push-to-app-collection: Generate app CR"
       command: |
@@ -40,8 +54,9 @@ steps:
           --name "<<parameters.app_name>>-unique" \
           --app-name "<<parameters.app_name>>" \
           --app-namespace "<<parameters.app_namespace>>" \
-          --app-version "$(cat .version)" \
+          --app-version "$(cat .app_version)" \
           --catalog "<<parameters.app_catalog>>" \
+          --config-version "$(cat .config_version)" \
           --disable-force-upgrade=<<parameters.disable_force_upgrade>> \
           --user-configmap-name "<<parameters.user_configmap_name>>" \
           --user-secret-name "<<parameters.user_secret_name>>" \
@@ -85,7 +100,7 @@ steps:
   - run:
       name: "architect/push-to-app-collection: Commit changes to the app collection repo"
       command: |
-        git -C .app-collection commit -m "update <<parameters.app_name>>-unique to $(cat .version)"
+        git -C .app-collection commit -m "update <<parameters.app_name>>-unique to $(cat .app_version)"
   - run:
       name: "architect/push-to-app-collection: Push changes to the app collection repo"
       command: |
@@ -116,4 +131,4 @@ steps:
   - run:
       name: "architect/push-to-app-collection: Cleanup"
       command: |
-        rm .version
+        rm .app_version .config_version
